---
extends:
  - airbnb
  - prettier
rules:
  react/jsx-filename-extension:
    - error
    - extensions:
      - ".js"
  import/no-extraneous-dependencies:
    - error
    -
      peerDependencies:
        - "src/**/*.js"
      devDependencies:
        - "*.js"
        - "test/**/*.js"
